### ISSUE TITLE
I tried to scrape one season but it got stuck after five games

### ISSUE THREAD

**Issue by hzblacksmith** [mcbarlowe/nba_scraper#16]
I tried scarping 19-20 season, but the program got stuck after game 0021900005. Is it because my IP got blocked from the NBA Stats?

**Comment by mcbarlowe** [comment]
What do you mean by got stuck? Did it error out? can you give me some more detail and the code you were running please?

**Comment by hzblacksmith** [comment]
I ran it again using only 1 game using this:
```
import nba_scraper.nba_scraper as ns
ns.scrape_game([21900001], data_format= 'csv')
```
and the output I got is:
`Scraping game id: 0021900001`
and there has been no update for 20 minutes.

I previously ran 
```
import nba_scraper.nba_scraper as ns
ns.scrape_season(2020, data_format= 'csv')
```

and the output is 
```Scraping game id: 0021900001
[1610612761]
Scraping game id: 0021900002
[1610612746]
Scraping game id: 0021900003
[1610612766]
Scraping game id: 0021900004
[1610612754]
Scraping game id: 0021900005
[1610612753]
```

and no more info popping out.

**Comment by hzblacksmith** [comment]
I just ran `scrape_season` again and now it seems to work! Perhaps the API call got stuck previously for some reason.

**Comment by hzblacksmith** [comment]
It seems that it works fine for the most time, there's once or twice it wasn't working. Thank you Matthew for this awesome scraper!

**Comment by mcbarlowe** [comment]
Yeah I made the scrape season function but if you find your having issues still with it lagging I would suggest using the `scrape_game` method for each game_id and then writing the resulting play by play to file so you don't have to repeat the process in case of a disconnect. If you need help calculating stats you can pass the output of the scraper to my [`nba_parser`](https://github.com/mcbarlowe/nba_parser)
