### ISSUE TITLE
Getting a JSONDecodeError

### ISSUE THREAD

**Issue by bennett-a** [mcbarlowe/nba_scraper#19]
I'm receiving a JSONDecodeError after game ID 0021800254 when scraping the 2019 season...

    JSONDecodeError                           Traceback (most recent call last)
    <ipython-input-5-fa487e61689b> in <module>
    ----> 1 nba_df = ns.scrape_season(2019)

    /opt/anaconda3/lib/python3.8/site-packages/nba_scraper/nba_scraper.py in scrape_season(season, data_format, data_dir)
        189         else:
        190             print(f"Scraping game id: 00{game}")
    --> 191             scraped_games.append(sf.main_scrape(f"00{game}"))
        192 
        193     if len(scraped_games) == 0:

    /opt/anaconda3/lib/python3.8/site-packages/nba_scraper/scrape_functions.py in main_scrape(game_id)
        705         game_df = game_df[game_df["period"] < 5]
        706     for period in range(1, game_df["period"].max() + 1):
    --> 707         lineups = get_lineup_api(game_id, period)
        708         periods.append(
        709             get_lineup(game_df[game_df["period"] == period].copy(), lineups, game_df,)

    /opt/anaconda3/lib/python3.8/site-packages/nba_scraper/scrape_functions.py in get_lineup_api(game_id, period)
        373 
        374     lineups_req = requests.get(url, headers=USER_AGENT)
    --> 375     lineup_req_dict = json.loads(lineups_req.text)
        376 
        377     return lineup_req_dict

    /opt/anaconda3/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant,     object_pairs_hook, **kw)
        355             parse_int is None and parse_float is None and
        356             parse_constant is None and object_pairs_hook is None and not kw):
    --> 357         return _default_decoder.decode(s)
        358     if cls is None:
        359         cls = JSONDecoder

    /opt/anaconda3/lib/python3.8/json/decoder.py in decode(self, s, _w)
        335 
        336         """
    --> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        338         end = _w(s, end).end()
        339         if end != len(s):

    /opt/anaconda3/lib/python3.8/json/decoder.py in raw_decode(self, s, idx)
        353             obj, end = self.scan_once(s, idx)
        354         except StopIteration as err:
    --> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
        356         return obj, end

    JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mcbarlowe** [comment]
I would advise scraping on a game by game basis because its possible they are limiting the API if you are hitting it a lot because I just scraped that game with no problem
```
❯ python test.py
Scraping game id: 0021800255
[1610612738]
      game_id  eventnum  ...    away_player_5  away_player_5_id
0  0021800255         2  ...  Emmanuel Mudiay           1626144
1  0021800255         4  ...  Emmanuel Mudiay           1626144
2  0021800255         7  ...  Emmanuel Mudiay           1626144
3  0021800255         8  ...  Emmanuel Mudiay           1626144
4  0021800255        10  ...  Emmanuel Mudiay           1626144
```
