### ISSUE TITLE
get_date_games function not pulling games before game id 021800110

### ISSUE THREAD

**Issue by mcbarlowe** [mcbarlowe/nba_scraper#5]
The `get_date_games` function in `scrape_functions` module is not pulling the early season game_ids for the 2019 season. I discovered this in writing integration tests for the function. I'm assigning this to me but if someone wants to jump on it I'd be happy to accept a pull request. @HarryShomer if you have any advice that would help but if you're busy don't worry I'll handle it. Will need all tests to pass in the test_integration.py file before merging into master

**Comment by HarryShomer** [comment]
I'll take a look now

**Comment by mcbarlowe** [comment]
I just pushed latest test to travis branch if you want to work there that will have all the tests you need

**Comment by mcbarlowe** [comment]
I will pull this fix into master after all the unit tests are written or until someone complains about it
